### ISSUE TITLE
Infinite loop if dependencies are empty

### ISSUE THREAD

**Issue by hatchette** [bertofer/npm-platform-dependencies#1]
Consider this: 
package.json:
 "postinstall": "npmpd"
 "darwinDependencies": {}

npm install will now be stuck in endless loop, because npmpd will call npm install without arguments.

**Comment by bortexz** [comment]
Fixed in https://github.com/bertofer/npm-platform-dependencies/commit/78985de9a5c35f7c2252d59195c527159e74488d and uploaded in v0.0.13, thanks for noticing :)
