### ISSUE TITLE
npm adds platform specific dependencies to regular dependencies section after npm install

### ISSUE THREAD

**Issue by renkei** [bertofer/npm-platform-dependencies#2]
I've defined a linuxDependencies section with two packages that should be installed on a linux plaform only. As documented, I've added npmpd to postinstall script. npm install works as expected but at the end of the installation process the two platform specific packages are automatically inserted into the regular dependencies section, so they are defined twice, in the dependencies section (that makes trouble on other platforms than linux) and in the linuxDependencies section.

System environment: Arch Linux ARM, npm 5.3.0, nodejs 8.4.0

**Comment by renkei** [comment]
Can be solved by adding '--no-save' to the npmArgs array in line 16 of index.js

**Comment by tdmalone** [comment]
@renkei You can edit `index.js` to add that :) It will then generate a pull request which @bertofer can easily merge in.

**Comment by jarrodbell** [comment]
Submitted a pull request #4 with this feature, and the ability to append any custom argument to the npm install process.

**Comment by bortexz** [comment]
This issue is solved in https://github.com/bertofer/npm-platform-dependencies/pull/4
